import StochasticToDeterministicLatents.Bridge
import StochasticToDeterministicLatents.Pricing
import StochasticToDeterministicLatents.Binary.Table

/-!
# Symmetries of binary tables

The row swap, column swap, and transpose generate the relabelings used by the
binary reduction.  This module represents those relabelings and transports
codes, information quantities, stochastic latents, optimality, determinization
costs, feasible kernels, contacts, and full-support seed setups across them.

## Attribution

The upstream ancestor is
[`DLorell/stoch_to_det`](https://github.com/DLorell/stoch_to_det), Apache-2.0.
Selected follow-on working material is adapted with public names and
module boundaries; it is unpublished and supplies no verification evidence.
-/

open scoped BigOperators

namespace StochasticToDeterministicLatents

noncomputable section

namespace Binary

/-! ## Cell symmetries -/

/-- Flip the two binary labels. -/
def bitFlip : Bit ≃ Bit where
  toFun := Equiv.swap (0 : Bit) 1
  invFun := Equiv.swap (0 : Bit) 1
  left_inv := Equiv.swap_apply_self (0 : Bit) 1
  right_inv := Equiv.swap_apply_self (0 : Bit) 1

/-- Swap the two rows of a binary table. -/
def swapRowsCell : Cell ≃ Cell :=
  Equiv.prodCongr bitFlip (Equiv.refl Bit)

/-- Swap the two columns of a binary table. -/
def swapColumnsCell : Cell ≃ Cell :=
  Equiv.prodCongr (Equiv.refl Bit) bitFlip

/-- Transpose a binary table. -/
def transposeCell : Cell ≃ Cell :=
  Equiv.prodComm Bit Bit

/-- The group syntax generated by row swap, column swap, and transpose. -/
inductive TableSymmetry
  | refl
  | swapRows
  | swapColumns
  | transpose
  | comp (first second : TableSymmetry)
  deriving DecidableEq

/-- The cell equivalence denoted by a table-symmetry expression. -/
def TableSymmetry.equiv : TableSymmetry → Cell ≃ Cell
  | .refl => Equiv.refl Cell
  | .swapRows => swapRowsCell
  | .swapColumns => swapColumnsCell
  | .transpose => transposeCell
  | .comp first second => first.equiv.trans second.equiv

private def boolXor (a b : Bool) : Bool :=
  if a then !b else b

private def bitEquiv : Bool → Bit ≃ Bit
  | false => Equiv.refl Bit
  | true => bitFlip

/-- Construct the canonical symmetry with the supplied transpose, row-flip,
and column-flip bits. -/
def TableSymmetry.ofBits : Bool × Bool × Bool → TableSymmetry
  | (false, false, false) => .refl
  | (false, true, false) => .swapRows
  | (false, false, true) => .swapColumns
  | (false, true, true) => .comp .swapRows .swapColumns
  | (true, false, false) => .transpose
  | (true, true, false) => .comp .transpose .swapRows
  | (true, false, true) => .comp .transpose .swapColumns
  | (true, true, true) => .comp .transpose (.comp .swapRows .swapColumns)

private def composeSymmetryBits
    (x y : Bool × Bool × Bool) : Bool × Bool × Bool :=
  let s := x.1
  let a := x.2.1
  let b := x.2.2
  let t := y.1
  let c := y.2.1
  let d := y.2.2
  (boolXor s t,
    if t then boolXor b c else boolXor a c,
    if t then boolXor a d else boolXor b d)

/-- The transpose, row-flip, and column-flip bits of a symmetry expression. -/
def TableSymmetry.toBits : TableSymmetry → Bool × Bool × Bool
  | .refl => (false, false, false)
  | .swapRows => (false, true, false)
  | .swapColumns => (false, false, true)
  | .transpose => (true, false, false)
  | .comp first second => composeSymmetryBits first.toBits second.toBits

/-- Normalize a symmetry expression to its canonical three-bit representative. -/
def TableSymmetry.normalize (r : TableSymmetry) : TableSymmetry :=
  TableSymmetry.ofBits r.toBits

private theorem equiv_ofBits_formula (s a b : Bool) :
    (TableSymmetry.ofBits (s, a, b)).equiv =
      if s then
        transposeCell.trans (Equiv.prodCongr (bitEquiv a) (bitEquiv b))
      else
        Equiv.prodCongr (bitEquiv a) (bitEquiv b) := by
  cases s <;> cases a <;> cases b <;>
    ext z <;> rcases z with ⟨x, y⟩ <;>
    fin_cases x <;> fin_cases y <;> rfl

private theorem bitEquiv_apply_apply (a b : Bool) (x : Bit) :
    bitEquiv b (bitEquiv a x) = bitEquiv (boolXor a b) x := by
  cases a <;> cases b <;> fin_cases x <;> rfl

private theorem equiv_ofBits_comp
    (x y : Bool × Bool × Bool) :
    (TableSymmetry.comp (TableSymmetry.ofBits x) (TableSymmetry.ofBits y)).equiv =
      (TableSymmetry.ofBits (composeSymmetryBits x y)).equiv := by
  rcases x with ⟨s, a, b⟩
  rcases y with ⟨t, c, d⟩
  cases s <;> cases t <;>
    ext z <;> rcases z with ⟨i, j⟩ <;>
    simp [TableSymmetry.equiv, equiv_ofBits_formula, composeSymmetryBits,
      boolXor, transposeCell, bitEquiv_apply_apply]

/-- Normalization preserves the denoted cell equivalence. -/
theorem TableSymmetry.normalize_equiv (r : TableSymmetry) :
    r.normalize.equiv = r.equiv := by
  induction r with
  | refl => rfl
  | swapRows => rfl
  | swapColumns => rfl
  | transpose => rfl
  | comp first second ihFirst ihSecond =>
      calc
        (TableSymmetry.comp first second).normalize.equiv =
            (TableSymmetry.comp first.normalize second.normalize).equiv := by
              exact (equiv_ofBits_comp first.toBits second.toBits).symm
        _ = first.equiv.trans second.equiv := by
              simp only [TableSymmetry.equiv, ihFirst, ihSecond]
        _ = (TableSymmetry.comp first second).equiv := rfl

/-- The inverse symmetry expression. -/
def TableSymmetry.inverse : TableSymmetry → TableSymmetry
  | .refl => .refl
  | .swapRows => .swapRows
  | .swapColumns => .swapColumns
  | .transpose => .transpose
  | .comp first second => .comp second.inverse first.inverse

/-- The inverse expression denotes the inverse cell equivalence. -/
theorem TableSymmetry.inverse_equiv (r : TableSymmetry) :
    r.inverse.equiv = r.equiv.symm := by
  induction r with
  | refl => rfl
  | swapRows =>
      ext ⟨x, y⟩ <;> fin_cases x <;> fin_cases y <;> rfl
  | swapColumns =>
      ext ⟨x, y⟩ <;> fin_cases x <;> fin_cases y <;> rfl
  | transpose =>
      ext ⟨x, y⟩ <;> fin_cases x <;> fin_cases y <;> rfl
  | comp first second ihFirst ihSecond =>
      simp [TableSymmetry.inverse, TableSymmetry.equiv, ihFirst, ihSecond]

/-! ## Law and code transport -/

/-- Transport a deterministic code contravariantly along an equivalence. -/
def transportCode {Ω Ω' γ : Type*}
    (e : Ω ≃ Ω') (g : Ω → γ) : Ω' → γ :=
  fun z => g (e.symm z)

/-- Relabel the output alphabet of a deterministic code. -/
def relabelCodeLabels {Ω γ δ : Type*}
    (e : γ ≃ δ) (g : Ω → γ) : Ω → δ :=
  fun z => e (g z)

/-- A pushforward along an equivalence has the expected pointwise formula. -/
theorem pushforward_apply_equiv {Ω Ω' : Type*} [Fintype Ω]
    [Fintype Ω'] [DecidableEq Ω'] (e : Ω ≃ Ω')
    (p : Ω → ℝ) (z : Ω') :
    pushforward e p z = p (e.symm z) := by
  unfold pushforward stoch_to_det.push
  apply Finset.sum_eq_single (e.symm z)
  · intro b hb hne
    have heb : e b = z := (Finset.mem_filter.mp hb).2
    exact (hne (e.apply_eq_iff_eq_symm_apply.mp heb)).elim
  · intro hnot
    exact (hnot (by simp)).elim

/-- Strict positivity is preserved by pushforward along an equivalence. -/
theorem pushforward_pos {Ω Ω' : Type*} [Fintype Ω]
    [Fintype Ω'] [DecidableEq Ω'] {p : Ω → ℝ}
    (hpos : ∀ z, 0 < p z) (e : Ω ≃ Ω') :
    ∀ z, 0 < pushforward e p z := by
  intro z
  rw [pushforward_apply_equiv]
  exact hpos _

/-- Pushing forward by an equivalence and then its inverse returns the law. -/
theorem pushforward_symm_pushforward {Ω Ω' : Type*}
    [Fintype Ω] [Fintype Ω'] [DecidableEq Ω] [DecidableEq Ω']
    (e : Ω ≃ Ω') (p : Ω → ℝ) :
    pushforward e.symm (pushforward e p) = p := by
  funext z
  rw [pushforward_apply_equiv, pushforward_apply_equiv]
  simp

/-- Successive pushforwards along equivalences compose. -/
@[simp] theorem pushforward_trans
    {A B C : Type*} [Fintype A] [Fintype B] [Fintype C]
    [DecidableEq A] [DecidableEq B] [DecidableEq C]
    (e : A ≃ B) (f : B ≃ C) (p : A → ℝ) :
    pushforward (e.trans f) p = pushforward f (pushforward e p) := by
  funext z
  calc
    pushforward (e.trans f) p z = p ((e.trans f).symm z) :=
      pushforward_apply_equiv (e.trans f) p z
    _ = p (e.symm (f.symm z)) := rfl
    _ = pushforward e p (f.symm z) := (pushforward_apply_equiv e p _).symm
    _ = pushforward f (pushforward e p) z :=
      (pushforward_apply_equiv f (pushforward e p) z).symm

/-- Transporting a code through an equivalence and back returns the code. -/
@[simp] theorem transportCode_transportCode
    {A B γ : Type*} (e : A ≃ B) (g : B → γ) :
    transportCode e (transportCode e.symm g) = g := by
  funext z
  simp [transportCode]

/-- Transport preserves the constant binary code. -/
@[simp] theorem transportCode_constantCode (e : Cell ≃ Cell) :
    transportCode e constantCode = constantCode := by
  funext z
  rfl

/-- Transport sends a singleton code to the singleton at the image cell. -/
theorem transportCode_singletonCode (e : Cell ≃ Cell) (cell : Cell) :
    transportCode e (singletonCode cell) = singletonCode (e cell) := by
  funext z
  by_cases h : e.symm z = cell
  · have hz : z = e cell := by
      apply e.symm.injective
      simpa using h
    simp [transportCode, singletonCode, hz]
  · have hz : z ≠ e cell := by
      intro hz
      apply h
      simp [hz]
    simp [transportCode, singletonCode, h, hz]

/-! ## Information transport -/

/-- Entropy of a random variable transports across a relabeled sample space. -/
theorem entropyOf_pushforward {Ω Ω' γ : Type*} [Fintype Ω] [Fintype Ω'] [Fintype γ]
    [DecidableEq Ω'] [DecidableEq γ] (e : Ω ≃ Ω') (p : Ω → ℝ) (f : Ω' → γ) :
    entropyOf f (pushforward e p) = entropyOf (f ∘ e) p := by
  unfold entropyOf stoch_to_det.Hvar pushforward
  rw [stoch_to_det.push_push]

/-- Conditional entropy transports across a relabeled sample space. -/
theorem condEntropy_pushforward {Ω Ω' γ δ : Type*}
    [Fintype Ω] [Fintype Ω'] [Fintype γ] [Fintype δ]
    [DecidableEq Ω'] [DecidableEq γ] [DecidableEq δ]
    (e : Ω ≃ Ω') (p : Ω → ℝ) (f : Ω' → γ) (g : Ω' → δ) :
    condEntropy f g (pushforward e p) =
      condEntropy (f ∘ e) (g ∘ e) p := by
  unfold condEntropy stoch_to_det.condH
  have hfg := entropyOf_pushforward e p (fun z => (f z, g z))
  have hg := entropyOf_pushforward e p g
  simp only [entropyOf] at hfg hg
  rw [hfg, hg]
  rfl

/-- Conditional mutual information transports across a relabeled sample space. -/
theorem condMutualInfo_pushforward {Ω Ω' γ δ ε : Type*} [Fintype Ω] [Fintype Ω']
    [Fintype γ] [Fintype δ] [Fintype ε] [DecidableEq Ω'] [DecidableEq γ]
    [DecidableEq δ] [DecidableEq ε] (e : Ω ≃ Ω') (p : Ω → ℝ)
    (f : Ω' → γ) (g : Ω' → δ) (h : Ω' → ε) :
    condMutualInfo f g h (pushforward e p) =
      condMutualInfo (f ∘ e) (g ∘ e) (h ∘ e) p := by
  unfold condMutualInfo stoch_to_det.condMI
  have hfh := entropyOf_pushforward e p (fun z => (f z, h z))
  have hgh := entropyOf_pushforward e p (fun z => (g z, h z))
  have hfgh := entropyOf_pushforward e p (fun z => (f z, g z, h z))
  have hh := entropyOf_pushforward e p h
  simp only [entropyOf] at hfh hgh hfgh hh
  rw [hfh, hgh, hfgh, hh]
  rfl

/-- Equivalence-recoding all three variables preserves conditional mutual information. -/
theorem condMutualInfo_congr_equiv
    {Ω γ δ ε γ' δ' ε' : Type*}
    [Fintype Ω] [Fintype γ] [Fintype δ] [Fintype ε]
    [Fintype γ'] [Fintype δ'] [Fintype ε']
    [DecidableEq γ] [DecidableEq δ] [DecidableEq ε]
    [DecidableEq γ'] [DecidableEq δ'] [DecidableEq ε']
    {p : Ω → ℝ} (hp : IsPMF p)
    (eg : γ ≃ γ') (ed : δ ≃ δ') (ee : ε ≃ ε')
    (f : Ω → γ) (g : Ω → δ) (h : Ω → ε) :
    condMutualInfo (fun w => eg (f w)) (fun w => ed (g w))
        (fun w => ee (h w)) p =
      condMutualInfo f g h p := by
  have hfh : entropyOf (fun w => (eg (f w), ee (h w))) p =
      entropyOf (fun w => (f w, h w)) p := by
    simpa using entropyOf_equiv hp (fun w => (f w, h w)) (Equiv.prodCongr eg ee)
  have hgh : entropyOf (fun w => (ed (g w), ee (h w))) p =
      entropyOf (fun w => (g w, h w)) p := by
    simpa using entropyOf_equiv hp (fun w => (g w, h w)) (Equiv.prodCongr ed ee)
  have hfgh : entropyOf (fun w => (eg (f w), ed (g w), ee (h w))) p =
      entropyOf (fun w => (f w, g w, h w)) p := by
    simpa using entropyOf_equiv hp (fun w => (f w, g w, h w))
      (Equiv.prodCongr eg (Equiv.prodCongr ed ee))
  have hh : entropyOf (fun w => ee (h w)) p = entropyOf h p :=
    entropyOf_equiv hp h ee
  simp only [entropyOf] at hfh hgh hfgh hh
  unfold condMutualInfo stoch_to_det.condMI
  rw [hfh, hgh, hfgh, hh]

/-- Equivalence-recoding a variable and its conditioner preserves conditional entropy. -/
theorem condEntropy_congr_equiv
    {Ω γ δ γ' δ' : Type*}
    [Fintype Ω] [Fintype γ] [Fintype δ] [Fintype γ'] [Fintype δ']
    [DecidableEq γ] [DecidableEq δ] [DecidableEq γ'] [DecidableEq δ']
    {p : Ω → ℝ} (hp : IsPMF p)
    (eg : γ ≃ γ') (ed : δ ≃ δ') (f : Ω → γ) (g : Ω → δ) :
    condEntropy (fun w => eg (f w)) (fun w => ed (g w)) p =
      condEntropy f g p := by
  have hfg : entropyOf (fun w => (eg (f w), ed (g w))) p =
      entropyOf (fun w => (f w, g w)) p := by
    simpa using entropyOf_equiv hp (fun w => (f w, g w)) (Equiv.prodCongr eg ed)
  have hg : entropyOf (fun w => ed (g w)) p = entropyOf g p :=
    entropyOf_equiv hp g ed
  simp only [entropyOf] at hfg hg
  unfold condEntropy stoch_to_det.condH
  rw [hfg, hg]

/-- Deterministic score is invariant under a permutation of canonical code labels. -/
theorem detScore_relabelCodeLabels
    {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    {p : α × β → ℝ} (hp : IsPMF p)
    (e : Fin (Fintype.card (α × β)) ≃ Fin (Fintype.card (α × β)))
    (g : Code α β) :
    detScore p (relabelCodeLabels e g) = detScore p g := by
  have hmi := condMutualInfo_congr_equiv hp
    (Equiv.refl α) (Equiv.refl β) e Prod.fst Prod.snd g
  have hx := condEntropy_congr_equiv hp e (Equiv.refl α) g Prod.fst
  have hy := condEntropy_congr_equiv hp e (Equiv.refl β) g Prod.snd
  simp only [Equiv.refl_apply] at hmi hx hy
  unfold detScore relabelCodeLabels
  rw [hmi, hx, hy]

/-- Pointwise determinization cost is invariant under a permutation of canonical labels. -/
theorem w3Cost_relabelCodeLabels
    {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    {p : α × β → ℝ} (L : Latent p)
    (e : Fin (Fintype.card (α × β)) ≃ Fin (Fintype.card (α × β)))
    (g : Code α β) :
    w3Cost L (relabelCodeLabels e g) = w3Cost L g := by
  have hmi := condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) (Equiv.refl (α × β)) e
    (fun w : L.ι × (α × β) => w.1) (fun w => w.2) (fun w => g w.2)
  have hh := condEntropy_congr_equiv L.joint_isPMF e (Equiv.refl L.ι)
    (fun w : L.ι × (α × β) => g w.2) (fun w => w.1)
  simp only [Equiv.refl_apply] at hmi hh
  unfold w3Cost relabelCodeLabels
  rw [hmi, hh]

end Binary

/-! ## Latent transport -/

namespace Latent

open Binary

/-- Push every component law through a binary-cell equivalence. -/
def relabel (e : Cell ≃ Cell) {p : Cell → ℝ} (L : Latent p) :
    Latent (pushforward e p) where
  ι := L.ι
  fin := L.fin
  dec := L.dec
  prior := L.prior
  comp := fun v => pushforward e (L.comp v)
  prior_isPMF := L.prior_isPMF
  comp_isPMF := fun v => pushforward_isPMF (L.comp_isPMF v)
  mixture := by
    intro z
    calc
      ∑ v, L.prior v * pushforward e (L.comp v) z =
          ∑ v, L.prior v * L.comp v (e.symm z) := by
            apply Finset.sum_congr rfl
            intro v _
            rw [Binary.pushforward_apply_equiv]
      _ = p (e.symm z) := L.mixture (e.symm z)
      _ = pushforward e p z := by rw [Binary.pushforward_apply_equiv]

/-- Pull an oriented latent back along the observable-cell equivalence. -/
def pullback (e : Cell ≃ Cell) {p : Cell → ℝ}
    (L : Latent (pushforward e p)) : Latent p where
  ι := L.ι
  fin := L.fin
  dec := L.dec
  prior := L.prior
  comp := fun v z => L.comp v (e z)
  prior_isPMF := L.prior_isPMF
  comp_isPMF := by
    intro v
    have hfun : (fun z => L.comp v (e z)) =
        pushforward e.symm (L.comp v) := by
      funext z
      rw [Binary.pushforward_apply_equiv]
      simp
    rw [hfun]
    exact pushforward_isPMF (L.comp_isPMF v)
  mixture := by
    intro z
    calc
      ∑ v, L.prior v * L.comp v (e z) = pushforward e p (e z) :=
        L.mixture (e z)
      _ = p z := by simp [Binary.pushforward_apply_equiv]

/-- Rename latent labels without changing their component laws. -/
def reindex {p : Cell → ℝ} (L : Latent p)
    {κ : Type} [Fintype κ] [DecidableEq κ]
    (u : κ ≃ L.ι) : Latent p where
  ι := κ
  fin := inferInstance
  dec := inferInstance
  prior := fun k => L.prior (u k)
  comp := fun k => L.comp (u k)
  prior_isPMF := by
    refine ⟨fun k => L.prior_isPMF.nonneg (u k), ?_⟩
    unfold stoch_to_det.mass
    calc
      ∑ k, L.prior (u k) = ∑ v, L.prior v := u.sum_comp L.prior
      _ = 1 := by simpa [stoch_to_det.mass] using L.prior_isPMF.total
  comp_isPMF := fun k => L.comp_isPMF (u k)
  mixture := by
    intro z
    calc
      ∑ k, L.prior (u k) * L.comp (u k) z =
          ∑ v, L.prior v * L.comp v z :=
        u.sum_comp (fun v => L.prior v * L.comp v z)
      _ = p z := L.mixture z

/-- Joint-law formula for observable relabeling. -/
theorem relabel_joint (e : Cell ≃ Cell) {p : Cell → ℝ} (L : Latent p) :
    (relabel e L).joint =
      pushforward (Equiv.prodCongr (Equiv.refl L.ι) e) L.joint := by
  funext ⟨v, z⟩
  change L.prior v * pushforward e (L.comp v) z =
    pushforward (Equiv.prodCongr (Equiv.refl L.ι) e) L.joint (v, z)
  rw [Binary.pushforward_apply_equiv e (L.comp v) z,
    Binary.pushforward_apply_equiv
      (Equiv.prodCongr (Equiv.refl L.ι) e) L.joint (v, z)]
  rfl

/-- Joint-law formula for inverse observable pullback. -/
theorem pullback_joint (e : Cell ≃ Cell) {p : Cell → ℝ}
    (L : Latent (pushforward e p)) :
    (pullback e L).joint =
      pushforward (Equiv.prodCongr (Equiv.refl L.ι) e.symm) L.joint := by
  funext ⟨v, z⟩
  change L.prior v * L.comp v (e z) =
    pushforward (Equiv.prodCongr (Equiv.refl L.ι) e.symm) L.joint (v, z)
  rw [Binary.pushforward_apply_equiv
    (Equiv.prodCongr (Equiv.refl L.ι) e.symm) L.joint (v, z)]
  rfl

/-- Joint-law formula for latent-label reindexing. -/
theorem reindex_joint {p : Cell → ℝ} (L : Latent p)
    {κ : Type} [Fintype κ] [DecidableEq κ] (u : κ ≃ L.ι) :
    (reindex L u).joint =
      pushforward (Equiv.prodCongr u.symm (Equiv.refl Cell)) L.joint := by
  funext ⟨v, z⟩
  change L.prior (u v) * L.comp (u v) z =
    pushforward (Equiv.prodCongr u.symm (Equiv.refl Cell)) L.joint (v, z)
  rw [Binary.pushforward_apply_equiv
    (Equiv.prodCongr u.symm (Equiv.refl Cell)) L.joint (v, z)]
  rfl

/-- Relabeling followed by pullback returns the original joint law. -/
theorem pullback_relabel_joint (e : Cell ≃ Cell) {p : Cell → ℝ} (L : Latent p) :
    (pullback e (relabel e L)).joint = L.joint := by
  funext ⟨v, z⟩
  change L.prior v * pushforward e (L.comp v) (e z) =
    L.prior v * L.comp v z
  rw [Binary.pushforward_apply_equiv]
  simp

private theorem condMutualInfo_comm
    {Ω A B K : Type*} [Fintype Ω] [Fintype A] [Fintype B] [Fintype K]
    [DecidableEq A] [DecidableEq B] [DecidableEq K]
    {m : Ω → ℝ} (hm : IsPMF m)
    (f : Ω → A) (g : Ω → B) (h : Ω → K) :
    condMutualInfo f g h m = condMutualInfo g f h m := by
  let e : A × (B × K) ≃ B × (A × K) :=
    { toFun := fun z => (z.2.1, (z.1, z.2.2))
      invFun := fun z => (z.2.1, (z.1, z.2.2))
      left_inv := by intro z; rcases z with ⟨a, b, k⟩; rfl
      right_inv := by intro z; rcases z with ⟨b, a, k⟩; rfl }
  have htrip :
      entropyOf (fun w => (f w, g w, h w)) m =
        entropyOf (fun w => (g w, f w, h w)) m := by
    simpa [e] using
      (entropyOf_equiv hm (fun w => (f w, g w, h w)) e).symm
  simp only [entropyOf] at htrip
  unfold condMutualInfo stoch_to_det.condMI
  rw [htrip]
  ring

private theorem score_relabel_product
    (ex ey : Bit ≃ Bit) {p : Cell → ℝ} (L : Latent p) :
    (relabel (Equiv.prodCongr ex ey) L).score = L.score := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold Latent.score stoch_to_det.Latent.score
  rw [show stoch_to_det.Latent.joint (relabel (Equiv.prodCongr ex ey) L) =
    pushforward ((Equiv.refl L.ι).prodCongr (Equiv.prodCongr ex ey)) L.joint from
      relabel_joint (Equiv.prodCongr ex ey) L]
  change
    condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1)
          (pushforward ((Equiv.refl L.ι).prodCongr (Equiv.prodCongr ex ey)) L.joint) +
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
          (pushforward ((Equiv.refl L.ι).prodCongr (Equiv.prodCongr ex ey)) L.joint) +
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
        (pushforward ((Equiv.refl L.ι).prodCongr (Equiv.prodCongr ex ey)) L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1) L.joint +
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2) L.joint +
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1) L.joint
  have hXY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    ex ey (Equiv.refl L.ι)
    (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1)
  have hLX := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) ex ey
    (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
  have hLY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) ey ex
    (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
  let E := (Equiv.refl L.ι).prodCongr (Equiv.prodCongr ex ey)
  have tXY :
      condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
          (fun w => w.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
          (fun w => w.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => ex w.2.1)
          (fun w => ey w.2.2) (fun w => w.1) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1))
      _ = _ := by simpa using hXY
  have tLX :
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => w.1)
          (fun w => ex w.2.1) (fun w => ey w.2.2) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2))
      _ = _ := by simpa using hLX
  have tLY :
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => w.1)
          (fun w => ey w.2.2) (fun w => ex w.2.1) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1))
      _ = _ := by simpa using hLY
  simpa [E] using congrArg₂ (· + ·) (congrArg₂ (· + ·) tXY tLX) tLY

private theorem score_relabel_transposedProduct
    (ex ey : Bit ≃ Bit) {p : Cell → ℝ} (L : Latent p) :
    (relabel (transposeCell.trans (Equiv.prodCongr ex ey)) L).score = L.score := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold Latent.score stoch_to_det.Latent.score
  rw [show stoch_to_det.Latent.joint
      (relabel (transposeCell.trans (Equiv.prodCongr ex ey)) L) =
    pushforward ((Equiv.refl L.ι).prodCongr
      (transposeCell.trans (Equiv.prodCongr ex ey))) L.joint from
      relabel_joint (transposeCell.trans (Equiv.prodCongr ex ey)) L]
  change
    condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1)
          (pushforward ((Equiv.refl L.ι).prodCongr
            (transposeCell.trans (Equiv.prodCongr ex ey))) L.joint) +
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
          (pushforward ((Equiv.refl L.ι).prodCongr
            (transposeCell.trans (Equiv.prodCongr ex ey))) L.joint) +
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
        (pushforward ((Equiv.refl L.ι).prodCongr
          (transposeCell.trans (Equiv.prodCongr ex ey))) L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1) L.joint +
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2) L.joint +
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1) L.joint
  have hXY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    ex ey (Equiv.refl L.ι)
    (fun w : L.ι × Cell => w.2.2) (fun w => w.2.1) (fun w => w.1)
  have hLX := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) ex ey
    (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
  have hLY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) ey ex
    (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
  have hcomm := condMutualInfo_comm L.joint_isPMF
    (fun w : L.ι × Cell => w.2.2) (fun w => w.2.1) (fun w => w.1)
  let E := (Equiv.refl L.ι).prodCongr
    (transposeCell.trans (Equiv.prodCongr ex ey))
  have tXY :
      condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
          (fun w => w.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.2.2) (fun w => w.2.1)
          (fun w => w.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => ex w.2.2)
          (fun w => ey w.2.1) (fun w => w.1) L.joint := by
        simpa [E, transposeCell, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1))
      _ = _ := by simpa using hXY
  have tLX :
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => w.1)
          (fun w => ex w.2.2) (fun w => ey w.2.1) L.joint := by
        simpa [E, transposeCell, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2))
      _ = _ := by simpa using hLX
  have tLY :
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => w.1)
          (fun w => ey w.2.1) (fun w => ex w.2.2) L.joint := by
        simpa [E, transposeCell, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1))
      _ = _ := by simpa using hLY
  rw [show condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
      (fun w => w.1) (pushforward E L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.2.2) (fun w => w.2.1)
        (fun w => w.1) L.joint from tXY]
  rw [show condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
      (fun w => w.2.2) (pushforward E L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
        (fun w => w.2.1) L.joint from tLX]
  rw [show condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
      (fun w => w.2.1) (pushforward E L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
        (fun w => w.2.2) L.joint from tLY]
  rw [hcomm]
  ring

/-- A binary table symmetry preserves latent score. -/
theorem score_relabel (r : TableSymmetry) {p : Cell → ℝ} (L : Latent p) :
    (relabel r.equiv L).score = L.score := by
  rw [← r.normalize_equiv]
  rcases hbits : r.toBits with ⟨s, a, b⟩
  cases s
  · rw [TableSymmetry.normalize, hbits, equiv_ofBits_formula]
    exact score_relabel_product (bitEquiv a) (bitEquiv b) L
  · rw [TableSymmetry.normalize, hbits, equiv_ofBits_formula]
    exact score_relabel_transposedProduct (bitEquiv a) (bitEquiv b) L

/-- Pulling a latent back through a binary table symmetry preserves its score. -/
theorem score_pullback (r : TableSymmetry) {p : Cell → ℝ}
    (L : Latent (pushforward r.equiv p)) :
    (pullback r.equiv L).score = L.score := by
  have hjoint :
      (pullback r.equiv L).joint = (relabel r.inverse.equiv L).joint := by
    rw [pullback_joint, relabel_joint, r.inverse_equiv]
  calc
    (pullback r.equiv L).score = (relabel r.inverse.equiv L).score := by
      unfold Latent.score stoch_to_det.Latent.score
      rw [show stoch_to_det.Latent.joint (pullback r.equiv L) =
        stoch_to_det.Latent.joint (relabel r.inverse.equiv L) from hjoint]
      rfl
    _ = L.score := score_relabel r.inverse L

/-- Renaming latent labels preserves latent score. -/
theorem score_reindex {p : Cell → ℝ} (L : Latent p)
    {κ : Type} [Fintype κ] [DecidableEq κ] (u : κ ≃ L.ι) :
    (reindex L u).score = L.score := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold Latent.score stoch_to_det.Latent.score
  rw [show stoch_to_det.Latent.joint (reindex L u) =
    pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint from
      reindex_joint L u]
  change
    condMutualInfo (fun w : κ × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1)
          (pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint) +
        condMutualInfo (fun w : κ × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
          (pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint) +
      condMutualInfo (fun w : κ × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
        (pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint) =
      condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1) L.joint +
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2) L.joint +
      condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1) L.joint
  have hXY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl Bit) (Equiv.refl Bit) u.symm
    (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1)
  have hLX := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    u.symm (Equiv.refl Bit) (Equiv.refl Bit)
    (fun w : L.ι × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2)
  have hLY := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    u.symm (Equiv.refl Bit) (Equiv.refl Bit)
    (fun w : L.ι × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1)
  let E := u.symm.prodCongr (Equiv.refl Cell)
  have tXY :
      condMutualInfo (fun w : κ × Cell => w.2.1) (fun w => w.2.2)
          (fun w => w.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
          (fun w => w.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => w.2.1) (fun w => w.2.2)
          (fun w => u.symm w.1) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : κ × Cell => w.2.1) (fun w => w.2.2) (fun w => w.1))
      _ = _ := by simpa using hXY
  have tLX :
      condMutualInfo (fun w : κ × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.1)
          (fun w => w.2.2) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => u.symm w.1) (fun w => w.2.1)
          (fun w => w.2.2) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : κ × Cell => w.1) (fun w => w.2.1) (fun w => w.2.2))
      _ = _ := by simpa using hLX
  have tLY :
      condMutualInfo (fun w : κ × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) (pushforward E L.joint) =
        condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2.2)
          (fun w => w.2.1) L.joint := by
    calc
      _ = condMutualInfo (fun w : L.ι × Cell => u.symm w.1) (fun w => w.2.2)
          (fun w => w.2.1) L.joint := by
        simpa [E, Function.comp_def] using
          (Binary.condMutualInfo_pushforward E L.joint
            (fun w : κ × Cell => w.1) (fun w => w.2.2) (fun w => w.2.1))
      _ = _ := by simpa using hLY
  simpa [E] using congrArg₂ (· + ·) (congrArg₂ (· + ·) tXY tLX) tLY

end Latent

open Binary

private theorem latentScoreRange_bddBelow (p : Cell → ℝ) :
    BddBelow (Set.range fun L : Latent p => L.score) := by
  refine ⟨0, ?_⟩
  rintro _ ⟨L, rfl⟩
  exact L.score_nonneg

private theorem binaryW3CostRange_bddBelow {p : Cell → ℝ} (L : Latent p) :
    BddBelow (Set.range fun g : BinaryCode => w3Cost L g) := by
  refine ⟨0, ?_⟩
  rintro _ ⟨g, rfl⟩
  unfold w3Cost
  exact add_nonneg
    (condMutualInfo_nonneg L.joint_isPMF
      (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2))
    (mul_nonneg (by norm_num)
      (condEntropy_nonneg L.joint_isPMF
        (fun w : L.ι × Cell => g w.2) (fun w => w.1)))

namespace Binary

/-- Binary table symmetries preserve the stochastic optimum. -/
theorem tau_pushforward (r : TableSymmetry) (p : Cell → ℝ) (hp : IsPMF p) :
    tau (pushforward r.equiv p) = tau p := by
  let hpR : IsPMF (pushforward r.equiv p) := pushforward_isPMF hp
  let _ : Nonempty (Latent p) :=
    ⟨Latent.ofFunction hp constantCode⟩
  let _ : Nonempty (Latent (pushforward r.equiv p)) :=
    ⟨Latent.ofFunction hpR constantCode⟩
  unfold tau
  apply le_antisymm
  · refine le_ciInf fun L => ?_
    calc
      (⨅ K : Latent (pushforward r.equiv p), K.score) ≤
          (Latent.relabel r.equiv L).score :=
        ciInf_le (latentScoreRange_bddBelow _) _
      _ = L.score := Latent.score_relabel r L
  · refine le_ciInf fun L => ?_
    calc
      (⨅ K : Latent p, K.score) ≤ (Latent.pullback r.equiv L).score :=
        ciInf_le (latentScoreRange_bddBelow _) _
      _ = L.score := Latent.score_pullback r L

end Binary

namespace Latent

/-- Score optimality transports forward through a binary table symmetry. -/
theorem score_eq_tau_relabel
    (r : TableSymmetry) {p : Cell → ℝ} (hp : IsPMF p) (L : Latent p)
    (hL : L.score = tau p) :
    (relabel r.equiv L).score = tau (pushforward r.equiv p) := by
  rw [score_relabel, hL, Binary.tau_pushforward r p hp]

/-- Score optimality transports through inverse observable pullback. -/
theorem score_eq_tau_pullback
    (r : TableSymmetry) {p : Cell → ℝ} (hp : IsPMF p)
    (L : Latent (pushforward r.equiv p))
    (hL : L.score = tau (pushforward r.equiv p)) :
    (pullback r.equiv L).score = tau p := by
  rw [score_pullback, hL, Binary.tau_pushforward r p hp]

end Latent

/-! ## Determinization-cost transport -/

namespace Binary

/-- Relabeling a whole latent and transporting a fixed code preserves its cost. -/
theorem w3Cost_relabel
    (e : Cell ≃ Cell) {p : Cell → ℝ} (L : Latent p) (g : BinaryCode) :
    w3Cost (Latent.relabel e L) (transportCode e g) = w3Cost L g := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold w3Cost
  rw [Latent.relabel_joint]
  change
    condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2)
        (fun w => g (e.symm w.2))
        (pushforward ((Equiv.refl L.ι).prodCongr e) L.joint) +
      3 * condEntropy (fun w : L.ι × Cell => g (e.symm w.2)) (fun w => w.1)
        (pushforward ((Equiv.refl L.ι).prodCongr e) L.joint) =
    condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2) L.joint +
      3 * condEntropy (fun w : L.ι × Cell => g w.2) (fun w => w.1) L.joint
  let eid : Fin (Fintype.card Cell) ≃ Fin (Fintype.card Cell) := Equiv.refl _
  have hMI := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) e eid
    (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2)
  rw [Binary.condMutualInfo_pushforward, Binary.condEntropy_pushforward]
  apply congrArg₂ (fun x y : ℝ => x + 3 * y)
  · convert hMI using 1
    all_goals congr 1
    funext w
    rcases w with ⟨i, z⟩
    simp only [eid, Function.comp_def, Equiv.prodCongr_apply,
      Prod.map_apply, Equiv.refl_apply, Equiv.symm_apply_apply]
  · simp [Function.comp_def, Equiv.prodCongr_apply]

/-- Pullback has the corresponding contravariant fixed-code cost formula. -/
theorem w3Cost_pullback
    (e : Cell ≃ Cell) {p : Cell → ℝ}
    (L : Latent (pushforward e p)) (g : BinaryCode) :
    w3Cost (Latent.pullback e L) g = w3Cost L (transportCode e g) := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold w3Cost
  rw [Latent.pullback_joint]
  change
    condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2)
        (pushforward ((Equiv.refl L.ι).prodCongr e.symm) L.joint) +
      3 * condEntropy (fun w : L.ι × Cell => g w.2) (fun w => w.1)
        (pushforward ((Equiv.refl L.ι).prodCongr e.symm) L.joint) =
    condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2)
        (fun w => g (e.symm w.2)) L.joint +
      3 * condEntropy (fun w : L.ι × Cell => g (e.symm w.2)) (fun w => w.1) L.joint
  have hMI := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    (Equiv.refl L.ι) e.symm (Equiv.refl (Fin (Fintype.card Cell)))
    (fun w : L.ι × Cell => w.1) (fun w => w.2)
    (fun w => transportCode e g w.2)
  have hH := Binary.condEntropy_congr_equiv L.joint_isPMF
    (Equiv.refl (Fin (Fintype.card Cell))) (Equiv.refl L.ι)
    (fun w : L.ι × Cell => transportCode e g w.2) (fun w => w.1)
  rw [Binary.condMutualInfo_pushforward, Binary.condEntropy_pushforward]
  apply congrArg₂ (fun x y : ℝ => x + 3 * y)
  · convert hMI using 1 <;> rfl
  · convert hH using 1 <;> rfl

/-- Pulling back the inverse-transported code gives the original oriented cost. -/
theorem w3Cost_pullback_inverse
    (e : Cell ≃ Cell) {p : Cell → ℝ}
    (L : Latent (pushforward e p)) (g : BinaryCode) :
    w3Cost (Latent.pullback e L) (transportCode e.symm g) = w3Cost L g := by
  rw [w3Cost_pullback, Binary.transportCode_transportCode]

/-- Renaming latent labels preserves every fixed-code cost. -/
theorem w3Cost_reindex
    {p : Cell → ℝ} (L : Latent p)
    {κ : Type} [Fintype κ] [DecidableEq κ]
    (u : κ ≃ L.ι) (g : BinaryCode) :
    w3Cost (Latent.reindex L u) g = w3Cost L g := by
  let : Fintype L.ι := L.fin
  let : DecidableEq L.ι := L.dec
  unfold w3Cost
  rw [Latent.reindex_joint]
  change
    condMutualInfo (fun w : κ × Cell => w.1) (fun w => w.2) (fun w => g w.2)
        (pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint) +
      3 * condEntropy (fun w : κ × Cell => g w.2) (fun w => w.1)
        (pushforward (u.symm.prodCongr (Equiv.refl Cell)) L.joint) =
    condMutualInfo (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2) L.joint +
      3 * condEntropy (fun w : L.ι × Cell => g w.2) (fun w => w.1) L.joint
  have hMI := Binary.condMutualInfo_congr_equiv L.joint_isPMF
    u.symm (Equiv.refl Cell) (Equiv.refl (Fin (Fintype.card Cell)))
    (fun w : L.ι × Cell => w.1) (fun w => w.2) (fun w => g w.2)
  have hH := Binary.condEntropy_congr_equiv L.joint_isPMF
    (Equiv.refl (Fin (Fintype.card Cell))) u.symm
    (fun w : L.ι × Cell => g w.2) (fun w => w.1)
  rw [Binary.condMutualInfo_pushforward, Binary.condEntropy_pushforward]
  apply congrArg₂ (fun x y : ℝ => x + 3 * y)
  · convert hMI using 1
    rfl
  · convert hH using 1
    rfl

/-- Whole-latent observable relabeling preserves the best determinization cost. -/
theorem w3_relabel (e : Cell ≃ Cell) {p : Cell → ℝ} (L : Latent p) :
    w3 (Latent.relabel e L) = w3 L := by
  let _ : Nonempty BinaryCode := ⟨constantCode⟩
  unfold w3
  apply le_antisymm
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost (Latent.relabel e L) h) ≤
          w3Cost (Latent.relabel e L) (transportCode e g) :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost L g := w3Cost_relabel e L g
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost L h) ≤ w3Cost L (transportCode e.symm g) :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost (Latent.relabel e L) g := by
        symm
        simpa using w3Cost_relabel e L (transportCode e.symm g)

/-- Inverse pullback preserves the best determinization cost. -/
theorem w3_pullback (e : Cell ≃ Cell) {p : Cell → ℝ}
    (L : Latent (pushforward e p)) :
    w3 (Latent.pullback e L) = w3 L := by
  let _ : Nonempty BinaryCode := ⟨constantCode⟩
  unfold w3
  apply le_antisymm
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost (Latent.pullback e L) h) ≤
          w3Cost (Latent.pullback e L) (transportCode e.symm g) :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost L g := w3Cost_pullback_inverse e L g
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost L h) ≤ w3Cost L (transportCode e g) :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost (Latent.pullback e L) g := (w3Cost_pullback e L g).symm

/-- Renaming latent labels preserves the best determinization cost. -/
theorem w3_reindex {p : Cell → ℝ} (L : Latent p)
    {κ : Type} [Fintype κ] [DecidableEq κ] (u : κ ≃ L.ι) :
    w3 (Latent.reindex L u) = w3 L := by
  let _ : Nonempty BinaryCode := ⟨constantCode⟩
  unfold w3
  apply le_antisymm
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost (Latent.reindex L u) h) ≤
          w3Cost (Latent.reindex L u) g :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost L g := w3Cost_reindex L u g
  · refine le_ciInf fun g => ?_
    calc
      (⨅ h : BinaryCode, w3Cost L h) ≤ w3Cost L g :=
        ciInf_le (binaryW3CostRange_bddBelow _) _
      _ = w3Cost (Latent.reindex L u) g := (w3Cost_reindex L u g).symm

end Binary

/-! ## Feasibility and contact transport -/

private theorem rowMarginal_pushforward_product
    (ex ey : Bit ≃ Bit) (q : Cell → ℝ) :
    stoch_to_det.mX (pushforward (Equiv.prodCongr ex ey) q) =
      pushforward ex (stoch_to_det.mX q) := by
  unfold stoch_to_det.mX pushforward
  rw [stoch_to_det.push_push, stoch_to_det.push_push]
  rfl

private theorem columnMarginal_pushforward_product
    (ex ey : Bit ≃ Bit) (q : Cell → ℝ) :
    stoch_to_det.mY (pushforward (Equiv.prodCongr ex ey) q) =
      pushforward ey (stoch_to_det.mY q) := by
  unfold stoch_to_det.mY pushforward
  rw [stoch_to_det.push_push, stoch_to_det.push_push]
  rfl

private theorem rowMarginal_pushforward_transposedProduct
    (ex ey : Bit ≃ Bit) (q : Cell → ℝ) :
    stoch_to_det.mX
        (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) q) =
      pushforward ex (stoch_to_det.mY q) := by
  unfold stoch_to_det.mX stoch_to_det.mY pushforward transposeCell
  rw [stoch_to_det.push_push, stoch_to_det.push_push]
  rfl

private theorem columnMarginal_pushforward_transposedProduct
    (ex ey : Bit ≃ Bit) (q : Cell → ℝ) :
    stoch_to_det.mY
        (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) q) =
      pushforward ey (stoch_to_det.mX q) := by
  unfold stoch_to_det.mX stoch_to_det.mY pushforward transposeCell
  rw [stoch_to_det.push_push, stoch_to_det.push_push]
  rfl

private theorem lambda_univ_pushforward_product
    (ex ey : Bit ≃ Bit) (w : Cell → ℝ) (u v : Bit → ℝ) :
    Lambda (Finset.univ : Finset Cell)
        (pushforward (Equiv.prodCongr ex ey) w) u v =
      Lambda (Finset.univ : Finset Cell) w
        (pushforward ex.symm u) (pushforward ey.symm v) := by
  let e := Equiv.prodCongr ex ey
  have h := e.sum_comp (fun z : Cell =>
    pushforward e w z * u z.1 ^ ((2 : ℝ) / 3) * v z.2 ^ ((2 : ℝ) / 3))
  simp only [Lambda, stoch_to_det.Lambda]
  calc
    (∑ z, pushforward e w z * u z.1 ^ ((2 : ℝ) / 3) *
        v z.2 ^ ((2 : ℝ) / 3)) =
        ∑ z, pushforward e w (e z) * u (e z).1 ^ ((2 : ℝ) / 3) *
          v (e z).2 ^ ((2 : ℝ) / 3) := h.symm
    _ = ∑ z, w z * u (ex z.1) ^ ((2 : ℝ) / 3) *
          v (ey z.2) ^ ((2 : ℝ) / 3) := by
      apply Finset.sum_congr rfl
      intro z _
      rw [Binary.pushforward_apply_equiv]
      rw [e.symm_apply_apply]
      rfl
    _ = ∑ z, w z * pushforward ex.symm u z.1 ^ ((2 : ℝ) / 3) *
          pushforward ey.symm v z.2 ^ ((2 : ℝ) / 3) := by
      apply Finset.sum_congr rfl
      intro z _
      rw [Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv]
      simp

private theorem lambda_univ_pushforward_transposedProduct
    (ex ey : Bit ≃ Bit) (w : Cell → ℝ) (u v : Bit → ℝ) :
    Lambda (Finset.univ : Finset Cell)
        (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) w) u v =
      Lambda (Finset.univ : Finset Cell) w
        (pushforward ey.symm v) (pushforward ex.symm u) := by
  let e := transposeCell.trans (Equiv.prodCongr ex ey)
  have h := e.sum_comp (fun z : Cell =>
    pushforward e w z * u z.1 ^ ((2 : ℝ) / 3) * v z.2 ^ ((2 : ℝ) / 3))
  simp only [Lambda, stoch_to_det.Lambda]
  calc
    (∑ z, pushforward e w z * u z.1 ^ ((2 : ℝ) / 3) *
        v z.2 ^ ((2 : ℝ) / 3)) =
        ∑ z, pushforward e w (e z) * u (e z).1 ^ ((2 : ℝ) / 3) *
          v (e z).2 ^ ((2 : ℝ) / 3) := h.symm
    _ = ∑ z, w z * u (ex z.2) ^ ((2 : ℝ) / 3) *
          v (ey z.1) ^ ((2 : ℝ) / 3) := by
      apply Finset.sum_congr rfl
      intro z _
      rw [Binary.pushforward_apply_equiv]
      rw [e.symm_apply_apply]
      rfl
    _ = ∑ z, w z * pushforward ey.symm v z.1 ^ ((2 : ℝ) / 3) *
          pushforward ex.symm u z.2 ^ ((2 : ℝ) / 3) := by
      apply Finset.sum_congr rfl
      intro z _
      rw [Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv]
      simp [mul_assoc, mul_left_comm, mul_comm]

private theorem feasible_pushforward_product
    (ex ey : Bit ≃ Bit) {w : Cell → ℝ}
    (hw : Feasible (Finset.univ : Finset Cell) w) :
    Feasible (Finset.univ : Finset Cell)
      (pushforward (Equiv.prodCongr ex ey) w) := by
  refine ⟨?_, ?_⟩
  · intro z _
    rw [Binary.pushforward_apply_equiv]
    exact hw.1 _ (Finset.mem_univ _)
  · intro u v hu hv
    calc
      Lambda (Finset.univ : Finset Cell)
          (pushforward (Equiv.prodCongr ex ey) w) u v =
          Lambda (Finset.univ : Finset Cell) w
            (pushforward ex.symm u) (pushforward ey.symm v) :=
        lambda_univ_pushforward_product ex ey w u v
      _ ≤ 1 := hw.2 _ _ (pushforward_isPMF hu) (pushforward_isPMF hv)

private theorem feasible_pushforward_transposedProduct
    (ex ey : Bit ≃ Bit) {w : Cell → ℝ}
    (hw : Feasible (Finset.univ : Finset Cell) w) :
    Feasible (Finset.univ : Finset Cell)
      (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) w) := by
  refine ⟨?_, ?_⟩
  · intro z _
    rw [Binary.pushforward_apply_equiv]
    exact hw.1 _ (Finset.mem_univ _)
  · intro u v hu hv
    calc
      Lambda (Finset.univ : Finset Cell)
          (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) w) u v =
          Lambda (Finset.univ : Finset Cell) w
            (pushforward ey.symm v) (pushforward ex.symm u) :=
        lambda_univ_pushforward_transposedProduct ex ey w u v
      _ ≤ 1 := hw.2 _ _ (pushforward_isPMF hv) (pushforward_isPMF hu)

namespace Binary

/-- Feasibility on the full binary universe is invariant under table symmetry. -/
theorem feasible_pushforward
    (r : TableSymmetry) {w : Cell → ℝ}
    (hw : Feasible (Finset.univ : Finset Cell) w) :
    Feasible (Finset.univ : Finset Cell) (pushforward r.equiv w) := by
  rw [← r.normalize_equiv]
  rcases hbits : r.toBits with ⟨s, a, b⟩
  cases s
  · simpa [TableSymmetry.normalize, hbits, equiv_ofBits_formula] using
      feasible_pushforward_product (bitEquiv a) (bitEquiv b) hw
  · simpa [TableSymmetry.normalize, hbits, equiv_ofBits_formula] using
      feasible_pushforward_transposedProduct (bitEquiv a) (bitEquiv b) hw

end Binary

private theorem isContact_pushforward_product
    (ex ey : Bit ≃ Bit) {w q : Cell → ℝ}
    (hq : IsContact (Finset.univ : Finset Cell) w q) :
    IsContact (Finset.univ : Finset Cell)
      (pushforward (Equiv.prodCongr ex ey) w)
      (pushforward (Equiv.prodCongr ex ey) q) := by
  refine ⟨pushforward_isPMF hq.1, ?_, ?_⟩
  · intro z hz
    simp at hz
  · intro z _
    rw [Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv,
      rowMarginal_pushforward_product, columnMarginal_pushforward_product,
      Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv]
    simpa using hq.2.2 ((Equiv.prodCongr ex ey).symm z) (Finset.mem_univ _)

private theorem isContact_pushforward_transposedProduct
    (ex ey : Bit ≃ Bit) {w q : Cell → ℝ}
    (hq : IsContact (Finset.univ : Finset Cell) w q) :
    IsContact (Finset.univ : Finset Cell)
      (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) w)
      (pushforward (transposeCell.trans (Equiv.prodCongr ex ey)) q) := by
  let e := transposeCell.trans (Equiv.prodCongr ex ey)
  refine ⟨pushforward_isPMF hq.1, ?_, ?_⟩
  · intro z hz
    simp at hz
  · intro z _
    rw [Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv,
      rowMarginal_pushforward_transposedProduct,
      columnMarginal_pushforward_transposedProduct,
      Binary.pushforward_apply_equiv, Binary.pushforward_apply_equiv]
    have hc := hq.2.2 (e.symm z) (Finset.mem_univ _)
    simpa [e, transposeCell, mul_assoc, mul_left_comm, mul_comm] using hc

namespace Binary

/-- Contact equations on the full binary universe are invariant under table symmetry. -/
theorem isContact_pushforward
    (r : TableSymmetry) {w q : Cell → ℝ}
    (hq : IsContact (Finset.univ : Finset Cell) w q) :
    IsContact (Finset.univ : Finset Cell)
      (pushforward r.equiv w) (pushforward r.equiv q) := by
  rw [← r.normalize_equiv]
  rcases hbits : r.toBits with ⟨s, a, b⟩
  cases s
  · simpa [TableSymmetry.normalize, hbits, equiv_ofBits_formula] using
      isContact_pushforward_product (bitEquiv a) (bitEquiv b) hq
  · simpa [TableSymmetry.normalize, hbits, equiv_ofBits_formula] using
      isContact_pushforward_transposedProduct (bitEquiv a) (bitEquiv b) hq

/-- The full binary cell universe is connected by row/column adjacency. -/
theorem univ_isConnected :
    IsConnected (Finset.univ : Finset Cell) := by
  intro z _ w _
  let mid : Cell := (z.1, w.2)
  exact Relation.ReflTransGen.trans
    (Relation.ReflTransGen.single
      ⟨Finset.mem_univ z, Finset.mem_univ mid, Or.inl rfl⟩)
    (Relation.ReflTransGen.single
      ⟨Finset.mem_univ mid, Finset.mem_univ w, Or.inr rfl⟩)

/-- A strictly positive binary law has the full binary cell universe as support. -/
theorem support_eq_univ_of_pos
    {p : Cell → ℝ} (hpos : ∀ z, 0 < p z) :
    support p = Finset.univ := by
  ext z
  simp [support, stoch_to_det.support, (hpos z).ne']

end Binary

/-! ## Full-support seed setups -/

namespace SeedSetup

/-- Relabel every part of a full-support binary seed setup. -/
def relabel
    {p : Cell → ℝ} (S : SeedSetup p) (hpos : ∀ z, 0 < p z)
    (r : TableSymmetry) : SeedSetup (pushforward r.equiv p) where
  isPMF := pushforward_isPMF S.isPMF
  conn := by
    rw [show stoch_to_det.support (pushforward r.equiv p) = Finset.univ from
      Binary.support_eq_univ_of_pos (Binary.pushforward_pos hpos r.equiv)]
    exact Binary.univ_isConnected
  L := Latent.relabel r.equiv S.L
  w := pushforward r.equiv S.w
  feasible := by
    have hOld : stoch_to_det.Feasible (stoch_to_det.support p) S.w := S.feasible
    rw [show stoch_to_det.support p = Finset.univ from
      Binary.support_eq_univ_of_pos hpos] at hOld
    have hNew := Binary.feasible_pushforward r hOld
    rw [show stoch_to_det.support (pushforward r.equiv p) = Finset.univ from
      Binary.support_eq_univ_of_pos (Binary.pushforward_pos hpos r.equiv)]
    exact hNew
  optimal := Latent.score_eq_tau_relabel r S.isPMF S.L S.optimal
  contact := by
    intro v hv
    have hOld : stoch_to_det.IsContact (stoch_to_det.support p)
        S.w (S.L.comp v) := S.contact v hv
    rw [show stoch_to_det.support p = Finset.univ from
      Binary.support_eq_univ_of_pos hpos] at hOld
    have hNew := Binary.isContact_pushforward r hOld
    have hs : stoch_to_det.support (pushforward r.equiv p) = Finset.univ :=
      Binary.support_eq_univ_of_pos (Binary.pushforward_pos hpos r.equiv)
    exact hs.symm ▸ hNew
  prior_pos := S.prior_pos

/-- Pull an oriented full-support binary seed setup back to the original law. -/
def pullback
    {p : Cell → ℝ} (r : TableSymmetry)
    (S : SeedSetup (pushforward r.equiv p))
    (hp : IsPMF p) (hpos : ∀ z, 0 < p z) : SeedSetup p where
  isPMF := hp
  conn := by
    rw [show stoch_to_det.support p = Finset.univ from
      Binary.support_eq_univ_of_pos hpos]
    exact Binary.univ_isConnected
  L := Latent.pullback r.equiv S.L
  w := pushforward r.equiv.symm S.w
  feasible := by
    have hOrientedPos := Binary.pushforward_pos hpos r.equiv
    have hOld : stoch_to_det.Feasible
        (stoch_to_det.support (pushforward r.equiv p)) S.w := S.feasible
    rw [show stoch_to_det.support (pushforward r.equiv p) = Finset.univ from
      Binary.support_eq_univ_of_pos hOrientedPos] at hOld
    have hInv := Binary.feasible_pushforward r.inverse hOld
    rw [r.inverse_equiv] at hInv
    rw [show stoch_to_det.support p = Finset.univ from
      Binary.support_eq_univ_of_pos hpos]
    exact hInv
  optimal := Latent.score_eq_tau_pullback r hp S.L S.optimal
  contact := by
    intro v hv
    have hOrientedPos := Binary.pushforward_pos hpos r.equiv
    have hOld : stoch_to_det.IsContact
        (stoch_to_det.support (pushforward r.equiv p)) S.w (S.L.comp v) :=
      S.contact v hv
    rw [show stoch_to_det.support (pushforward r.equiv p) = Finset.univ from
      Binary.support_eq_univ_of_pos hOrientedPos] at hOld
    have hInv := Binary.isContact_pushforward r.inverse hOld
    rw [r.inverse_equiv] at hInv
    have hcomp : pushforward r.equiv.symm (S.L.comp v) =
        (Latent.pullback r.equiv S.L).comp v := by
      funext z
      simp [Binary.pushforward_apply_equiv, Latent.pullback]
    rw [hcomp] at hInv
    rw [show stoch_to_det.support p = Finset.univ from
      Binary.support_eq_univ_of_pos hpos]
    exact hInv
  prior_pos := S.prior_pos

end SeedSetup

end

end StochasticToDeterministicLatents
