import StochasticToDeterministicLatents.Binary.FactorTwo.Contact

/-!
# The tangent certificate in closed form

At a contact law -- one whose diagonal cells multiply to `u ^ 2` and whose
cubic vanishes at `u` -- the four values of `tangentCert` collapse to two
rational functions of the cells.  The two diagonal values are equal, and the
two off-diagonal values are a swapped pair.

`tangentCert q z = -3 lg (q z) + 2 lg (mX q z.1) + 2 lg (mY q z.2)` is a ratio
of cells and marginals, so each value is the logarithm of a rational function.
What the two hypotheses buy is that the ratio simplifies: on the diagonal the
four marginals collapse to `certDiagonal`, a function of the diagonal mass and
`u` alone, and off the diagonal the marginal product collapses to
`u ^ 2 + b - b c`, giving `certOffDiagonal`.

This is what makes an explicit reference law usable as an affine minorant of
`Phi` elsewhere: its certificate is the logarithms of three rational numbers,
computable from the cells, rather than four logarithms of an implicit
optimum.  `log_two_mul_phi_contact` is the same closed form
paired against the law itself, which is `Phi` there.

## Attribution

The upstream ancestor is
[`DLorell/stoch_to_det`](https://github.com/DLorell/stoch_to_det), Apache-2.0.
Selected follow-on working material is adapted with public names and
module boundaries; it is unpublished and supplies no verification evidence.
-/

namespace StochasticToDeterministicLatents.Binary

variable {q : RealTable} {u : ℝ}

/-! ## The two closed forms -/

/-- The diagonal value of the tangent certificate at a contact law, before the
logarithm: a function of the diagonal mass `s` and the top root `u` alone. -/
noncomputable def certDiagonal (s u : ℝ) : ℝ := (s + 2 * u) / (s + u) ^ 2

/-- The off-diagonal value of the tangent certificate at a contact law, before
the logarithm.  The two off-diagonal cells give `certOffDiagonal b c u` and
`certOffDiagonal c b u`. -/
noncomputable def certOffDiagonal (b c u : ℝ) : ℝ := b ^ 3 / (u ^ 2 + b - b * c) ^ 2

/-! ## Two algebraic identities -/

/-- The quartic identity behind the diagonal collapse.  It writes the
difference between the certificate's diagonal numerator and `certDiagonal`'s in
the ideal generated by the quadratic `a ^ 2 - s a + u ^ 2` and the cubic, so
that both vanishing forces the two to agree. -/
private theorem diag_identity (a s u w : ℝ) :
    (s + u) ^ 2 * (a ^ 2 + (1 - s) * a + w) ^ 2 - (s + 2 * u) * a ^ 3
      = (a ^ 2 - s * a + u ^ 2) *
          ((s + u) ^ 2 * (a ^ 2 + (2 - s) * a + 2 * w - u ^ 2) - (s + 2 * u) * a + u ^ 2)
        + (u ^ 3 - (1 - s) * u ^ 2 - w * (u + s)) *
          ((u ^ 3 - (1 - s) * u ^ 2 - w * (u + s)) + 2 * u ^ 2 - 2 * a * (s + u)) := by
  ring

/-- On the diagonal the two marginals through a cell collapse. -/
private theorem diag_ratio {a d b c u : ℝ} (ha : 0 < a) (hd : 0 < d) (hu : 0 < u)
    (hm : a + b + c + d = 1) (had : a * d = u ^ 2)
    (hf : u ^ 3 - (b + c) * u ^ 2 - b * c * (u + a + d) = 0) :
    (a + b) ^ 2 * (a + c) ^ 2 / a ^ 3 = certDiagonal (a + d) u := by
  have hquad : a ^ 2 - (a + d) * a + u ^ 2 = 0 := by linear_combination -had
  have hlin : 1 - (a + d) = b + c := by linarith
  have hfactor : a ^ 2 + (1 - (a + d)) * a + b * c = (a + b) * (a + c) := by
    rw [hlin]; ring
  have hcubic : u ^ 3 - (1 - (a + d)) * u ^ 2 - b * c * (u + (a + d)) = 0 := by
    rw [hlin]; linarith
  have hid := diag_identity a (a + d) u (b * c)
  rw [hquad, hcubic, zero_mul, zero_add, hfactor] at hid
  have ha3 : a ^ 3 ≠ 0 := pow_ne_zero _ ha.ne'
  have hsu : (a + d + u) ^ 2 ≠ 0 := pow_ne_zero _ (by positivity)
  unfold certDiagonal
  field_simp
  nlinarith [hid]

/-- Off the diagonal the two marginals through a cell multiply to a function of
that cell, the opposite cell, and `u`. -/
private theorem off_products {a d b c u : ℝ} (hm : a + b + c + d = 1)
    (had : a * d = u ^ 2) :
    (a + b) * (d + b) = u ^ 2 + b - b * c ∧ (a + c) * (d + c) = u ^ 2 + c - b * c := by
  refine ⟨by linear_combination had + b * hm, by linear_combination had + c * hm⟩

/-! ## Collecting three logarithms -/

/-- The certificate's combination of logarithms, on a diagonal cell. -/
private theorem logb_of_ratio {x y z K : ℝ} (hx : 0 < x) (hy : 0 < y) (hz : 0 < z)
    (hK : y ^ 2 * z ^ 2 / x ^ 3 = K) :
    -3 * Real.logb 2 x + 2 * Real.logb 2 y + 2 * Real.logb 2 z = Real.logb 2 K := by
  rw [← hK]
  simp only [Real.logb]
  rw [Real.log_div (by positivity) (by positivity),
    Real.log_mul (pow_ne_zero 2 hy.ne') (pow_ne_zero 2 hz.ne'),
    Real.log_pow, Real.log_pow, Real.log_pow]
  push_cast
  ring

/-- The certificate's combination of logarithms, on an off-diagonal cell. -/
private theorem logb_of_ratio_inv {x y z L : ℝ} (hx : 0 < x) (hy : 0 < y) (hz : 0 < z)
    (hL : x ^ 3 / (y * z) ^ 2 = L) :
    -3 * Real.logb 2 x + 2 * Real.logb 2 y + 2 * Real.logb 2 z = -Real.logb 2 L := by
  rw [← hL]
  simp only [Real.logb]
  rw [Real.log_div (by positivity) (by positivity), Real.log_pow, Real.log_pow,
    Real.log_mul hy.ne' hz.ne']
  push_cast
  ring

/-! ## The four values -/

/-- **The tangent certificate at a contact law, cell by cell.**  The two
diagonal values are the same rational function of the diagonal mass and `u`;
the two off-diagonal values are a swapped pair.  The hypotheses are the two
that define a contact law: the diagonal cells multiply to `u ^ 2`, and `u` is a
root of the cubic. -/
theorem tangentCert_contact_values (hq : IsPMF q) (hpos : FullSupport q) (hu : 0 < u)
    (had : entryA q * entryD q = u ^ 2) (hroot : cubic q u = 0) :
    tangentCert q (0, 0) = Real.logb 2 (certDiagonal (diagonalMass q) u)
      ∧ tangentCert q (1, 1) = Real.logb 2 (certDiagonal (diagonalMass q) u)
      ∧ tangentCert q (0, 1) = -Real.logb 2 (certOffDiagonal (entryB q) (entryC q) u)
      ∧ tangentCert q (1, 0) = -Real.logb 2 (certOffDiagonal (entryC q) (entryB q) u) := by
  have ha : 0 < q (0, 0) := hpos (0, 0)
  have hb : 0 < q (0, 1) := hpos (0, 1)
  have hc : 0 < q (1, 0) := hpos (1, 0)
  have hd : 0 < q (1, 1) := hpos (1, 1)
  have hm : q (0, 0) + q (0, 1) + q (1, 0) + q (1, 1) = 1 := by
    have ht := hq.total
    rwa [stoch_to_det.mass, sum_cells] at ht
  have had' : q (0, 0) * q (1, 1) = u ^ 2 := had
  have hf : u ^ 3 - (q (0, 1) + q (1, 0)) * u ^ 2
      - q (0, 1) * q (1, 0) * (u + q (0, 0) + q (1, 1)) = 0 := by
    rw [cubic, offDiagonalMass, offDiagonalProduct_eq, diagonalMass,
      entryA, entryB, entryC, entryD] at hroot
    linear_combination hroot
  have hs : diagonalMass q = q (0, 0) + q (1, 1) := rfl
  have hdiagA := diag_ratio ha hd hu hm had' hf
  have hdiagD : (q (1, 0) + q (1, 1)) ^ 2 * (q (0, 1) + q (1, 1)) ^ 2 / q (1, 1) ^ 3
      = certDiagonal (q (0, 0) + q (1, 1)) u := by
    have h := diag_ratio (a := q (1, 1)) (d := q (0, 0)) (b := q (1, 0)) (c := q (0, 1))
      hd ha hu (by linarith) (by linear_combination had') (by linear_combination hf)
    rw [show q (1, 1) + q (0, 0) = q (0, 0) + q (1, 1) from add_comm _ _] at h
    rw [← h]; ring
  have hoff := off_products hm had'
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [tangentCert, marginalX_zero, marginalY_zero, hs]
    exact logb_of_ratio ha (by positivity) (by positivity) hdiagA
  · rw [tangentCert, marginalX_one, marginalY_one, hs]
    exact logb_of_ratio hd (by positivity) (by positivity) hdiagD
  · rw [tangentCert, marginalX_zero, marginalY_one]
    refine logb_of_ratio_inv hb (by positivity) (by positivity) ?_
    rw [certOffDiagonal, entryB, entryC,
      show u ^ 2 + q (0, 1) - q (0, 1) * q (1, 0)
        = (q (0, 0) + q (0, 1)) * (q (0, 1) + q (1, 1)) from by
          linear_combination -hoff.1]
  · rw [tangentCert, marginalX_one, marginalY_zero]
    refine logb_of_ratio_inv hc (by positivity) (by positivity) ?_
    rw [certOffDiagonal, entryB, entryC,
      show u ^ 2 + q (1, 0) - q (1, 0) * q (0, 1)
        = (q (1, 0) + q (1, 1)) * (q (0, 0) + q (1, 0)) from by
          linear_combination -hoff.2]

/-- **`Phi` at a contact law, in the same closed form.**  Pairing the
certificate with the law it was built at returns `Phi` there, so the four
values above give `Phi` as three logarithms weighted by the diagonal mass and
the two off-diagonal cells.  Natural-log units. -/
theorem log_two_mul_phi_contact (hq : IsPMF q) (hpos : FullSupport q) (hu : 0 < u)
    (had : entryA q * entryD q = u ^ 2) (hroot : cubic q u = 0) :
    Real.log 2 * Phi q
      = diagonalMass q * Real.log (certDiagonal (diagonalMass q) u)
        - entryB q * Real.log (certOffDiagonal (entryB q) (entryC q) u)
        - entryC q * Real.log (certOffDiagonal (entryC q) (entryB q) u) := by
  obtain ⟨h00, h11, h01, h10⟩ := tangentCert_contact_values hq hpos hu had hroot
  rw [← tangentCert_self q hq, sum_cells, h00, h01, h10, h11]
  simp only [Real.logb, diagonalMass, entryA, entryB, entryC, entryD]
  have hl : Real.log 2 ≠ 0 := (Real.log_pos one_lt_two).ne'
  field_simp
  ring

end StochasticToDeterministicLatents.Binary
